---
- hosts: dev
  become: True
  tasks:
    - name: Install python pip
      apt:
        name: python-pip
        update_cache: yes
        state: present
    - name: Install docker
      apt:
        name: docker
        state: present
    - name: start docker
      ansible.builtin.systemd:
        service: docker
        state: started
        enabled: yes
    - name: Install docker-py python module
      pip:
        name: docker-py
        state: present
    - name: Start the container
      docker_container:
        name: springapp
        image: "yogeshwaran1998/springapp:{{DOCKER_TAG}}"
        state: started
        published_ports:
          - 0.0.0.0:8080:8080
